version: '3'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      DJANGO_MIGRATE: "on"
      START_SERVER: "on"
    env_file:
      - .env
  redis:
    image: redis:6.0.5
    ports:
      - "56379:6379"
